### ISSUE TITLE
Responsible Disclosure of High Severity Vulnerabilities in PBBoard Forum Software

### ISSUE THREAD

**Issue by UmerAdeemCheema** [pbboard/PBBoard-3.0.4#10]
Dear PBBoard Team,

I am a Security Researcher and Penetration Tester. Upon conducting a security assessment of the Open Source Repository of the PBBoard Forum Software, I have identified several high-severity vulnerabilities that could potentially pose a significant risk to organizations utilizing your software.

I am reaching out to inform your team about these vulnerabilities and to collaborate on implementing effective solutions. I believe that by working together, we can enhance the security of the PBBoard Forum Software and protect organizations from potential threats.

Please allow vulnerability reporting at https://github.com/pbboard/PBBoard-3.0.4/security for reporting these vulnerabilities to ensure that your team can promptly investigate and address the identified issues. I am committed to providing all necessary details and assistance to facilitate a smooth resolution.

I appreciate your attention to this matter and look forward to contributing to the ongoing improvement of the PBBoard Forum Software's security.

**Comment by zizoom305** [comment]
try now

**Comment by UmerAdeemCheema** [comment]
You have created a Security Policy but have not enabled the Private vulnerability reporting. Once you have enabled the Private vulnerability reporting, I would be happy to report the vulnerability there.

**Comment by sulaiman0dawod** [comment]
To reporting a vulnerability to pbboard/PBBoard-3.0.4
[](https://github.com/pbboard/PBBoard-3.0.4/security/advisories/new)
