### ISSUE TITLE
xss vulnerability

### ISSUE THREAD

**Issue by Christynorl** [pbboard/PBBoard-3.0.4#3]
hi,@sulaiman0dawod . I found an xss vulnerability, which may affect the security of users. I submitted the specific information in the huntr community, please click the link below to view
[link](https://huntr.dev/bounties/da563551-081d-4ef1-854f-fbc3ce4fffef/)
https://huntr.dev/bounties/da563551-081d-4ef1-854f-fbc3ce4fffef/

**Comment by sulaiman0dawod** [comment]
> hi,@sulaiman0dawod . I found an xss vulnerability, which may affect the security of users. I submitted the specific information in the huntr community, please click the link below to view [link](https://huntr.dev/bounties/da563551-081d-4ef1-854f-fbc3ce4fffef/) https://huntr.dev/bounties/da563551-081d-4ef1-854f-fbc3ce4fffef/

hi 
good job [Christy__](https://github.com/Christynorl)  
has now been out ADD XSS attacks filter in file: [pbboardCodeparse.class.php](https://github.com/pbboard/PBBoard-3.0.4/commit/8c7d596b557589f812dec434c162bd7b1b90973f) 

https://github.com/pbboard/PBBoard-3.0.4/commit/8c7d596b557589f812dec434c162bd7b1b90973f

Thank you for reporting.

**Comment by Christynorl** [comment]
hi,@sulaiman0dawod.Could you please verify my report by this link [link](https://huntr.dev/bounties/da563551-081d-4ef1-854f-fbc3ce4fffef/).This is very helpful for me to test my tools. Thanks a lot.And it looks like the bug was successfully fixed.

**Comment by Christynorl** [comment]
And I am making a vulnerability detection tool, if possible, please apply for a cve for this vulnerability, thank you very much

**Comment by sulaiman0dawod** [comment]
> hi,@sulaiman0dawod . Could you please verify my report by this link [link](https://huntr.dev/bounties/da563551-081d-4ef1-854f-fbc3ce4fffef/).This is very helpful for me to test my tools. Thanks a lot.And it looks like the bug was successfully fixed.

**Done.**

**Comment by sulaiman0dawod** [comment]
![bugfixed](https://user-images.githubusercontent.com/15679600/215781691-c42e9d1e-6af4-4c3f-998b-ca64bc4d31a6.jpg)
