### ISSUE TITLE
security report

### ISSUE THREAD

**Issue by Christynorl** [pbboard/PBBoard-3.0.4#4]
hi @sulaiman0dawod ,👋
Excuse me again.
A member of our team has tested the project again and found that the filter you selected is not safe. I submitted the report to the huntr community again for privacy reasons, please click the link below to view and confirm. [link](https://huntr.dev/bounties/6624ff84-7d77-4cd3-bcfa-f9a91d05ebd8)https://huntr.dev/bounties/6624ff84-7d77-4cd3-bcfa-f9a91d05ebd8
As for the fix for this vulnerability, my suggestion is to choose a more secure, well-used filter.Thanks.

**Comment by sulaiman0dawod** [comment]
I will see what I can do about the filter
If you have a suggestion, tell me
Thanks

**Comment by Christynorl** [comment]
hi,I will help you improve the xss filter when I am free, maybe tomorrow or next week.
Now I still need you to vertify this bug on this website as before.[https://huntr.dev/bounties/6624ff84-7d77-4cd3-bcfa-f9a91d05ebd8].Thanks

**Comment by sulaiman0dawod** [comment]
OK Don't worry about fix xss filter
I fixed it and Update XSS filtering

https://github.com/pbboard/PBBoard-3.0.4/commit/a3e24e86cffd7b4c8f8a575f09dc2316010ab715

**Comment by Christynorl** [comment]
hi @sulaiman0dawod ,👋,
Well done.Can you please change the status of those two reports I submitted to fixed in the huntr community now.And please watch the picture.![img](https://github.com/Christynorl/hunt_imgs/blob/main/20230201100603.png)  thank you.
The links to the two reports are [link1](https://huntr.dev/bounties/da563551-081d-4ef1-854f-fbc3ce4fffef/)      [link2](https://huntr.dev/bounties/6624ff84-7d77-4cd3-bcfa-f9a91d05ebd8/)

**Comment by Christynorl** [comment]
After submitting the fix, there is an option to assign for a cve number, if possible, please apply for these two reports

**Comment by sulaiman0dawod** [comment]
Mark as fixed It does not work 
Commit SHA not found in repository
look at the picture
![bugfixed2](https://user-images.githubusercontent.com/15679600/215984065-8633efad-38c6-4a2f-ba8b-1610a17be0bd.jpg)

**Comment by Christynorl** [comment]
hi @sulaiman0dawod ,
the first report [1](https://huntr.dev/bounties/da563551-081d-4ef1-854f-fbc3ce4fffef/) .The value of commit you need to use is
 8c7d596b557589f812dec434c162bd7b1b90973f
the second one [2](https://huntr.dev/bounties/6624ff84-7d77-4cd3-bcfa-f9a91d05ebd8/).The value of commit you need to use is a3e24e86cffd7b4c8f8a575f09dc2316010ab715

**Comment by sulaiman0dawod** [comment]
> hi @sulaiman0dawod , the first report [rep1](https://huntr.dev/bounties/da563551-081d-4ef1-854f-fbc3ce4fffef/) .The value of commit you need to use is [8c7d596](https://github.com/pbboard/PBBoard-3.0.4/commit/8c7d596b557589f812dec434c162bd7b1b90973f) the second one [rep2](https://huntr.dev/bounties/6624ff84-7d77-4cd3-bcfa-f9a91d05ebd8/).The value of commit you need to use is [a3e24e8](https://github.com/pbboard/PBBoard-3.0.4/commit/a3e24e86cffd7b4c8f8a575f09dc2316010ab715)

### It also didn't working 
give me a message: **Commit SHA not found in repository**

**Comment by Christynorl** [comment]
I recorded a video of a successful operation. Follow the operation in the video to see if it is successful
[video](https://drive.google.com/file/d/1xY9oHs_P5dGvLAM8-cztVMaOuK5UxRpf/view?usp=share_link)

**Comment by sulaiman0dawod** [comment]
see video 
https://youtu.be/0ZOK-WqvIYc

**Comment by Christynorl** [comment]
ok,i see.Can you please invite me to be one of the contributors to this project.Thanks a lot.![like this](https://drive.google.com/file/d/1OJuOvRp7236DLLyF8rCmhZWFHjw3Xdw3/view?usp=share_link)

**Comment by sulaiman0dawod** [comment]
> ok,i see.Can you please invite me to be one of the contributors to this project.Thanks a lot.![like this](https://github.com/Christynorl/hunt_imgs/blob/main/20230201211458.png)
hi @Christynorl Christy__
**Invitation has been sent**, ### please check your email

**Comment by Christynorl** [comment]
hi,i found the filter is stoll unsafe .Please check [link](https://huntr.dev/bounties/7a48fde5-5032-4d2f-b00f-882eebc411cd/)
Here is my suggestion：You can replace the previous xss_clean function with the following code
`	$data=htmlspecialchars_decode($data);
	$patterns = '/(<\w*\s)*(((on\w*=)*|(on\w*\s*=))*)/Ui';
	$replacement = '$1';
	$data = preg_replace($patterns, $replacement, $data);
	$data = str_ireplace('alert','***',$data);
	$data = str_ireplace('javascript','non_java',$data);
	return $data;`

**Comment by sulaiman0dawod** [comment]
I watched the changes you made
Are you sure it suffices?
I hope it does not affect the content of the posts
I suggest that the replacement be passed in the <> tags only !

**Comment by Christynorl** [comment]
Sorry I overlooked this.You can modify the rule to just replace the "alert" character with "al***ert" inside the tag

**Comment by Christynorl** [comment]
$replace1='${1}';
$pat1='/(<\w*\s)*(alert)(\w*\s>)*/Ui';
echo preg_replace($pat1,$replace1,$data);

**Comment by sulaiman0dawod** [comment]
try this

```
//filtering tags
		$regexcodexss = array();
		$regexcodexss[] = '#\&lt;(.*)\&gt;#siU';
		$regexcodexss[] = '#\<(.*)\>#siU';
		$data = preg_replace_callback($regexcodexss, function($matches) {
		$matches[1] = html_entity_decode($matches[1], ENT_COMPAT, 'UTF-8');
		$matches[1] = str_ireplace('alert', '**', $matches[1]);
		$matches[1] = str_replace('(', '**', $matches[1]);
		$matches[1] = str_replace(')', '**', $matches[1]);
		$matches[1] = str_ireplace('&lt;', '**', $matches[1]);
		$matches[1] = str_ireplace('document.cookie', 'documen*t.cooki*e', $matches[1]);
		$matches[1] = str_ireplace('onclick', 'on*click', $matches[1]);
		$matches[1] = str_ireplace('click', 'c*lick', $matches[1]);
		$matches[1] = str_ireplace('absolute',"a*bsolute",$matches[1]);
		$matches[1] = str_ireplace('equiv',"e*quiv",$matches[1]);
		$matches[1] = str_ireplace('refresh',"r*efresh",$matches[1]);
		$matches[1] = str_ireplace('meta',"m*eta",$matches[1]);
		$matches[1] = str_ireplace('input',"i*nput",$matches[1]);
		$matches[1] = str_ireplace('action',"a*ction",$matches[1]);
		return "<".$matches[1].">";
		}, $data);

```

Put it higher
`return $data;`

And inform me of the result

**Comment by Christynorl** [comment]
You need to replace
 `		$matches[1] = str_ireplace('onclick', 'on*click', $matches[1]);
		$matches[1] = str_ireplace('click', 'c*lick', $matches[1]);` 
with 
`$patterns = '/(<\w*\s)*(((on\w*=)*|(on\w*\s*=))*)/Ui';
		$replacement = '$1';
		$matches[1] = preg_replace($patterns, $replacement, $matches[1]);` ,
and replace
`$matches[1] = str_ireplace('document.cookie', 'documen*t.cooki*e', $matches[1]);`
with
`$matches[1] = str_ireplace('document', 'documen*t', $matches[1]);`
other codes are fine

**Comment by sulaiman0dawod** [comment]
wonderful ..
File has been approved  and updated: **pbboardCodeparse.class.php**

https://github.com/pbboard/PBBoard-3.0.4/commit/30a359be05e43d2bbfe9e5a9cc1368e0b23b59d5

good job [Christynorl](https://github.com/Christynorl)

**Comment by Christynorl** [comment]
It looks good.I also want to know how to switch the language of the project to English. I can't find where to do it, can you please introduce it for me.Thanks.

**Comment by Christynorl** [comment]
[sulaiman0dawod](https://github.com/sulaiman0dawod).I found that the keyword parameter was not encoded, which may cause page errors or other security problems.Please check this picture for results ![picture](https://github.com/Christynorl/hunt_imgs/blob/main/20230203195101.png)
And you can visit ```https://www.pbboard.info/forums/index.php?page=search&start=1&search_only=1&sort_order=desc&section=all&keyword=zyp%22%3E%3C%3E&sa=%D8%A3%D8%A8%D8%AD%D8%AB&attempt=1``` 
I suggest you use the following line of code
```
$keyword=htmlspecialchars($keyword)
```

**Comment by sulaiman0dawod** [comment]
Yes Now has been Enable Check All GETS value ($_GET) and disabled value HTML or Javascript codes again on Version 3.0.4

It also disable work of all HTML codes in the content and posts with many modifications to the file: **pbboardCodeparse.class.php**

**Note:**
It is Version 3.0.4 still under testing and has not yet been officially approved.
Version 3.0.4 will be released Maybe next week.
You can now make all updates from the admincp.
Then you can run the security checks again.

Thank you so much.
